/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'a' at '10/26/16 12:00 AM' with Gradle 3.0
 *
 * @author a, @date 10/26/16 12:00 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
